/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.tellenn.artifacts.api.models.AccountLeaderboardType
import com.tellenn.artifacts.api.models.CharacterLeaderboardType
import com.tellenn.artifacts.api.models.DataPageAccountLeaderboardSchema
import com.tellenn.artifacts.api.models.DataPageCharacterLeaderboardSchema

import com.fasterxml.jackson.annotation.JsonProperty

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.tellenn.artifacts.api.infrastructure.ApiClient
import com.tellenn.artifacts.api.infrastructure.ApiResponse
import com.tellenn.artifacts.api.infrastructure.ClientException
import com.tellenn.artifacts.api.infrastructure.ClientError
import com.tellenn.artifacts.api.infrastructure.ServerException
import com.tellenn.artifacts.api.infrastructure.ServerError
import com.tellenn.artifacts.api.infrastructure.MultiValueMap
import com.tellenn.artifacts.api.infrastructure.PartConfig
import com.tellenn.artifacts.api.infrastructure.RequestConfig
import com.tellenn.artifacts.api.infrastructure.RequestMethod
import com.tellenn.artifacts.api.infrastructure.ResponseType
import com.tellenn.artifacts.api.infrastructure.Success
import com.tellenn.artifacts.api.infrastructure.toMultiValue

class LeaderboardApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Get Accounts Leaderboard
     * Fetch leaderboard details.
     * @param sort Default sort by achievements points. (optional)
     * @param name Find a account by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageAccountLeaderboardSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getAccountsLeaderboardLeaderboardAccountsGet(sort: AccountLeaderboardType? = null, name: kotlin.String? = null, page: kotlin.Int? = 1, size: kotlin.Int? = 50) : DataPageAccountLeaderboardSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getAccountsLeaderboardLeaderboardAccountsGetWithHttpInfo(sort = sort, name = name, page = page, size = size)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DataPageAccountLeaderboardSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Accounts Leaderboard
     * Fetch leaderboard details.
     * @param sort Default sort by achievements points. (optional)
     * @param name Find a account by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse<DataPageAccountLeaderboardSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getAccountsLeaderboardLeaderboardAccountsGetWithHttpInfo(sort: AccountLeaderboardType?, name: kotlin.String?, page: kotlin.Int?, size: kotlin.Int?) : ApiResponse<DataPageAccountLeaderboardSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getAccountsLeaderboardLeaderboardAccountsGetRequestConfig(sort = sort, name = name, page = page, size = size)

        return@withContext request<Unit, DataPageAccountLeaderboardSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAccountsLeaderboardLeaderboardAccountsGet
     *
     * @param sort Default sort by achievements points. (optional)
     * @param name Find a account by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return RequestConfig
     */
    fun getAccountsLeaderboardLeaderboardAccountsGetRequestConfig(sort: AccountLeaderboardType?, name: kotlin.String?, page: kotlin.Int?, size: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (name != null) {
                    put("name", listOf(name.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (size != null) {
                    put("size", listOf(size.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/leaderboard/accounts",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get Characters Leaderboard
     * Fetch leaderboard details.
     * @param sort Default sort by combat total XP. (optional)
     * @param name Find a character by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageCharacterLeaderboardSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getCharactersLeaderboardLeaderboardCharactersGet(sort: CharacterLeaderboardType? = null, name: kotlin.String? = null, page: kotlin.Int? = 1, size: kotlin.Int? = 50) : DataPageCharacterLeaderboardSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getCharactersLeaderboardLeaderboardCharactersGetWithHttpInfo(sort = sort, name = name, page = page, size = size)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DataPageCharacterLeaderboardSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Characters Leaderboard
     * Fetch leaderboard details.
     * @param sort Default sort by combat total XP. (optional)
     * @param name Find a character by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse<DataPageCharacterLeaderboardSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getCharactersLeaderboardLeaderboardCharactersGetWithHttpInfo(sort: CharacterLeaderboardType?, name: kotlin.String?, page: kotlin.Int?, size: kotlin.Int?) : ApiResponse<DataPageCharacterLeaderboardSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getCharactersLeaderboardLeaderboardCharactersGetRequestConfig(sort = sort, name = name, page = page, size = size)

        return@withContext request<Unit, DataPageCharacterLeaderboardSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCharactersLeaderboardLeaderboardCharactersGet
     *
     * @param sort Default sort by combat total XP. (optional)
     * @param name Find a character by name. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return RequestConfig
     */
    fun getCharactersLeaderboardLeaderboardCharactersGetRequestConfig(sort: CharacterLeaderboardType?, name: kotlin.String?, page: kotlin.Int?, size: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (sort != null) {
                    put("sort", listOf(sort.toString()))
                }
                if (name != null) {
                    put("name", listOf(name.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (size != null) {
                    put("size", listOf(size.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/leaderboard/characters",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
