/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.tellenn.artifacts.api.models.DataPageMonsterSchema
import com.tellenn.artifacts.api.models.MonsterResponseSchema

import com.fasterxml.jackson.annotation.JsonProperty

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.tellenn.artifacts.api.infrastructure.ApiClient
import com.tellenn.artifacts.api.infrastructure.ApiResponse
import com.tellenn.artifacts.api.infrastructure.ClientException
import com.tellenn.artifacts.api.infrastructure.ClientError
import com.tellenn.artifacts.api.infrastructure.ServerException
import com.tellenn.artifacts.api.infrastructure.ServerError
import com.tellenn.artifacts.api.infrastructure.MultiValueMap
import com.tellenn.artifacts.api.infrastructure.PartConfig
import com.tellenn.artifacts.api.infrastructure.RequestConfig
import com.tellenn.artifacts.api.infrastructure.RequestMethod
import com.tellenn.artifacts.api.infrastructure.ResponseType
import com.tellenn.artifacts.api.infrastructure.Success
import com.tellenn.artifacts.api.infrastructure.toMultiValue

class MonstersApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Get All Monsters
     * Fetch monsters details.
     * @param name Name of the monster. (optional)
     * @param minLevel Monster minimum level. (optional)
     * @param maxLevel Monster maximum level. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageMonsterSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getAllMonstersMonstersGet(name: kotlin.String? = null, minLevel: kotlin.Int? = null, maxLevel: kotlin.Int? = null, drop: kotlin.String? = null, page: kotlin.Int? = 1, size: kotlin.Int? = 50) : DataPageMonsterSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getAllMonstersMonstersGetWithHttpInfo(name = name, minLevel = minLevel, maxLevel = maxLevel, drop = drop, page = page, size = size)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DataPageMonsterSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get All Monsters
     * Fetch monsters details.
     * @param name Name of the monster. (optional)
     * @param minLevel Monster minimum level. (optional)
     * @param maxLevel Monster maximum level. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse<DataPageMonsterSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getAllMonstersMonstersGetWithHttpInfo(name: kotlin.String?, minLevel: kotlin.Int?, maxLevel: kotlin.Int?, drop: kotlin.String?, page: kotlin.Int?, size: kotlin.Int?) : ApiResponse<DataPageMonsterSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getAllMonstersMonstersGetRequestConfig(name = name, minLevel = minLevel, maxLevel = maxLevel, drop = drop, page = page, size = size)

        return@withContext request<Unit, DataPageMonsterSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAllMonstersMonstersGet
     *
     * @param name Name of the monster. (optional)
     * @param minLevel Monster minimum level. (optional)
     * @param maxLevel Monster maximum level. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return RequestConfig
     */
    fun getAllMonstersMonstersGetRequestConfig(name: kotlin.String?, minLevel: kotlin.Int?, maxLevel: kotlin.Int?, drop: kotlin.String?, page: kotlin.Int?, size: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (name != null) {
                    put("name", listOf(name.toString()))
                }
                if (minLevel != null) {
                    put("min_level", listOf(minLevel.toString()))
                }
                if (maxLevel != null) {
                    put("max_level", listOf(maxLevel.toString()))
                }
                if (drop != null) {
                    put("drop", listOf(drop.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (size != null) {
                    put("size", listOf(size.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/monsters",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get Monster
     * Retrieve the details of a monster.
     * @param code The code of the monster.
     * @return MonsterResponseSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getMonsterMonstersCodeGet(code: kotlin.String) : MonsterResponseSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getMonsterMonstersCodeGetWithHttpInfo(code = code)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as MonsterResponseSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Monster
     * Retrieve the details of a monster.
     * @param code The code of the monster.
     * @return ApiResponse<MonsterResponseSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getMonsterMonstersCodeGetWithHttpInfo(code: kotlin.String) : ApiResponse<MonsterResponseSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getMonsterMonstersCodeGetRequestConfig(code = code)

        return@withContext request<Unit, MonsterResponseSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getMonsterMonstersCodeGet
     *
     * @param code The code of the monster.
     * @return RequestConfig
     */
    fun getMonsterMonstersCodeGetRequestConfig(code: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/monsters/{code}".replace("{"+"code"+"}", encodeURIComponent(code.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
