/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.tellenn.artifacts.api.models.DataPageResourceSchema
import com.tellenn.artifacts.api.models.GatheringSkill
import com.tellenn.artifacts.api.models.ResourceResponseSchema

import com.fasterxml.jackson.annotation.JsonProperty

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.tellenn.artifacts.api.infrastructure.ApiClient
import com.tellenn.artifacts.api.infrastructure.ApiResponse
import com.tellenn.artifacts.api.infrastructure.ClientException
import com.tellenn.artifacts.api.infrastructure.ClientError
import com.tellenn.artifacts.api.infrastructure.ServerException
import com.tellenn.artifacts.api.infrastructure.ServerError
import com.tellenn.artifacts.api.infrastructure.MultiValueMap
import com.tellenn.artifacts.api.infrastructure.PartConfig
import com.tellenn.artifacts.api.infrastructure.RequestConfig
import com.tellenn.artifacts.api.infrastructure.RequestMethod
import com.tellenn.artifacts.api.infrastructure.ResponseType
import com.tellenn.artifacts.api.infrastructure.Success
import com.tellenn.artifacts.api.infrastructure.toMultiValue

class ResourcesApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Get All Resources
     * Fetch resources details.
     * @param minLevel Skill minimum level. (optional)
     * @param maxLevel Skill maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageResourceSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getAllResourcesResourcesGet(minLevel: kotlin.Int? = null, maxLevel: kotlin.Int? = null, skill: GatheringSkill? = null, drop: kotlin.String? = null, page: kotlin.Int? = 1, size: kotlin.Int? = 50) : DataPageResourceSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getAllResourcesResourcesGetWithHttpInfo(minLevel = minLevel, maxLevel = maxLevel, skill = skill, drop = drop, page = page, size = size)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DataPageResourceSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get All Resources
     * Fetch resources details.
     * @param minLevel Skill minimum level. (optional)
     * @param maxLevel Skill maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse<DataPageResourceSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getAllResourcesResourcesGetWithHttpInfo(minLevel: kotlin.Int?, maxLevel: kotlin.Int?, skill: GatheringSkill?, drop: kotlin.String?, page: kotlin.Int?, size: kotlin.Int?) : ApiResponse<DataPageResourceSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getAllResourcesResourcesGetRequestConfig(minLevel = minLevel, maxLevel = maxLevel, skill = skill, drop = drop, page = page, size = size)

        return@withContext request<Unit, DataPageResourceSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAllResourcesResourcesGet
     *
     * @param minLevel Skill minimum level. (optional)
     * @param maxLevel Skill maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return RequestConfig
     */
    fun getAllResourcesResourcesGetRequestConfig(minLevel: kotlin.Int?, maxLevel: kotlin.Int?, skill: GatheringSkill?, drop: kotlin.String?, page: kotlin.Int?, size: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (minLevel != null) {
                    put("min_level", listOf(minLevel.toString()))
                }
                if (maxLevel != null) {
                    put("max_level", listOf(maxLevel.toString()))
                }
                if (skill != null) {
                    put("skill", listOf(skill.toString()))
                }
                if (drop != null) {
                    put("drop", listOf(drop.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (size != null) {
                    put("size", listOf(size.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/resources",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get Resource
     * Retrieve the details of a resource.
     * @param code The code of the resource.
     * @return ResourceResponseSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getResourceResourcesCodeGet(code: kotlin.String) : ResourceResponseSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getResourceResourcesCodeGetWithHttpInfo(code = code)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ResourceResponseSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Resource
     * Retrieve the details of a resource.
     * @param code The code of the resource.
     * @return ApiResponse<ResourceResponseSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getResourceResourcesCodeGetWithHttpInfo(code: kotlin.String) : ApiResponse<ResourceResponseSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getResourceResourcesCodeGetRequestConfig(code = code)

        return@withContext request<Unit, ResourceResponseSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getResourceResourcesCodeGet
     *
     * @param code The code of the resource.
     * @return RequestConfig
     */
    fun getResourceResourcesCodeGetRequestConfig(code: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/resources/{code}".replace("{"+"code"+"}", encodeURIComponent(code.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
