/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import com.tellenn.artifacts.api.models.DataPageDropRateSchema
import com.tellenn.artifacts.api.models.DataPageTaskFullSchema
import com.tellenn.artifacts.api.models.RewardResponseSchema
import com.tellenn.artifacts.api.models.Skill
import com.tellenn.artifacts.api.models.TaskFullResponseSchema
import com.tellenn.artifacts.api.models.TaskType

import com.fasterxml.jackson.annotation.JsonProperty

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.tellenn.artifacts.api.infrastructure.ApiClient
import com.tellenn.artifacts.api.infrastructure.ApiResponse
import com.tellenn.artifacts.api.infrastructure.ClientException
import com.tellenn.artifacts.api.infrastructure.ClientError
import com.tellenn.artifacts.api.infrastructure.ServerException
import com.tellenn.artifacts.api.infrastructure.ServerError
import com.tellenn.artifacts.api.infrastructure.MultiValueMap
import com.tellenn.artifacts.api.infrastructure.PartConfig
import com.tellenn.artifacts.api.infrastructure.RequestConfig
import com.tellenn.artifacts.api.infrastructure.RequestMethod
import com.tellenn.artifacts.api.infrastructure.ResponseType
import com.tellenn.artifacts.api.infrastructure.Success
import com.tellenn.artifacts.api.infrastructure.toMultiValue

class TasksApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * Get All Tasks Rewards
     * Fetch the list of all tasks rewards. To obtain these rewards, you must exchange 6 task coins with a tasks master.
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageDropRateSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getAllTasksRewardsTasksRewardsGet(page: kotlin.Int? = 1, size: kotlin.Int? = 50) : DataPageDropRateSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getAllTasksRewardsTasksRewardsGetWithHttpInfo(page = page, size = size)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DataPageDropRateSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get All Tasks Rewards
     * Fetch the list of all tasks rewards. To obtain these rewards, you must exchange 6 task coins with a tasks master.
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse<DataPageDropRateSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getAllTasksRewardsTasksRewardsGetWithHttpInfo(page: kotlin.Int?, size: kotlin.Int?) : ApiResponse<DataPageDropRateSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getAllTasksRewardsTasksRewardsGetRequestConfig(page = page, size = size)

        return@withContext request<Unit, DataPageDropRateSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAllTasksRewardsTasksRewardsGet
     *
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return RequestConfig
     */
    fun getAllTasksRewardsTasksRewardsGetRequestConfig(page: kotlin.Int?, size: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (size != null) {
                    put("size", listOf(size.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/tasks/rewards",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get All Tasks
     * Fetch the list of all tasks.
     * @param minLevel Minimum level. (optional)
     * @param maxLevel Maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param type The type of tasks. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageTaskFullSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getAllTasksTasksListGet(minLevel: kotlin.Int? = null, maxLevel: kotlin.Int? = null, skill: Skill? = null, type: TaskType? = null, page: kotlin.Int? = 1, size: kotlin.Int? = 50) : DataPageTaskFullSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getAllTasksTasksListGetWithHttpInfo(minLevel = minLevel, maxLevel = maxLevel, skill = skill, type = type, page = page, size = size)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DataPageTaskFullSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get All Tasks
     * Fetch the list of all tasks.
     * @param minLevel Minimum level. (optional)
     * @param maxLevel Maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param type The type of tasks. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse<DataPageTaskFullSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getAllTasksTasksListGetWithHttpInfo(minLevel: kotlin.Int?, maxLevel: kotlin.Int?, skill: Skill?, type: TaskType?, page: kotlin.Int?, size: kotlin.Int?) : ApiResponse<DataPageTaskFullSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getAllTasksTasksListGetRequestConfig(minLevel = minLevel, maxLevel = maxLevel, skill = skill, type = type, page = page, size = size)

        return@withContext request<Unit, DataPageTaskFullSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getAllTasksTasksListGet
     *
     * @param minLevel Minimum level. (optional)
     * @param maxLevel Maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param type The type of tasks. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return RequestConfig
     */
    fun getAllTasksTasksListGetRequestConfig(minLevel: kotlin.Int?, maxLevel: kotlin.Int?, skill: Skill?, type: TaskType?, page: kotlin.Int?, size: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (minLevel != null) {
                    put("min_level", listOf(minLevel.toString()))
                }
                if (maxLevel != null) {
                    put("max_level", listOf(maxLevel.toString()))
                }
                if (skill != null) {
                    put("skill", listOf(skill.toString()))
                }
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (size != null) {
                    put("size", listOf(size.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/tasks/list",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get Task
     * Retrieve the details of a task.
     * @param code The code of the task.
     * @return TaskFullResponseSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getTaskTasksListCodeGet(code: kotlin.String) : TaskFullResponseSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getTaskTasksListCodeGetWithHttpInfo(code = code)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TaskFullResponseSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Task
     * Retrieve the details of a task.
     * @param code The code of the task.
     * @return ApiResponse<TaskFullResponseSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getTaskTasksListCodeGetWithHttpInfo(code: kotlin.String) : ApiResponse<TaskFullResponseSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getTaskTasksListCodeGetRequestConfig(code = code)

        return@withContext request<Unit, TaskFullResponseSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getTaskTasksListCodeGet
     *
     * @param code The code of the task.
     * @return RequestConfig
     */
    fun getTaskTasksListCodeGetRequestConfig(code: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/tasks/list/{code}".replace("{"+"code"+"}", encodeURIComponent(code.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * Get Tasks Reward
     * Retrieve the details of a tasks reward.
     * @param code The code of the tasks reward.
     * @return RewardResponseSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun getTasksRewardTasksRewardsCodeGet(code: kotlin.String) : RewardResponseSchema = withContext(Dispatchers.IO) {
        val localVarResponse = getTasksRewardTasksRewardsCodeGetWithHttpInfo(code = code)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as RewardResponseSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Tasks Reward
     * Retrieve the details of a tasks reward.
     * @param code The code of the tasks reward.
     * @return ApiResponse<RewardResponseSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun getTasksRewardTasksRewardsCodeGetWithHttpInfo(code: kotlin.String) : ApiResponse<RewardResponseSchema?> = withContext(Dispatchers.IO) {
        val localVariableConfig = getTasksRewardTasksRewardsCodeGetRequestConfig(code = code)

        return@withContext request<Unit, RewardResponseSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getTasksRewardTasksRewardsCodeGet
     *
     * @param code The code of the tasks reward.
     * @return RequestConfig
     */
    fun getTasksRewardTasksRewardsCodeGetRequestConfig(code: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/tasks/rewards/{code}".replace("{"+"code"+"}", encodeURIComponent(code.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
