/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: standard,founder,gold_founder,vip_founder
 */

enum class AccountStatus(val value: kotlin.String) {

    @JsonProperty(value = "standard")
    standard("standard"),

    @JsonProperty(value = "founder")
    founder("founder"),

    @JsonProperty(value = "gold_founder")
    gold_founder("gold_founder"),

    @JsonProperty(value = "vip_founder")
    vip_founder("vip_founder");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AccountStatus) "$data" else null

        /**
         * Returns a valid [AccountStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AccountStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

