/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.AccountStatus

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param username Username.
 * @param member Member status.
 * @param status Account status.
 * @param skins Skins owned.
 * @param achievementsPoints Achievement points.
 * @param banned Banned.
 * @param badges Account badges.
 * @param banReason Ban reason.
 */


data class AccountDetails (

    /* Username. */
    @field:JsonProperty("username")
    val username: kotlin.String,

    /* Member status. */
    @field:JsonProperty("member")
    val member: kotlin.Boolean,

    /* Account status. */
    @field:JsonProperty("status")
    val status: AccountStatus,

    /* Skins owned. */
    @field:JsonProperty("skins")
    val skins: kotlin.collections.List<kotlin.Any>,

    /* Achievement points. */
    @field:JsonProperty("achievements_points")
    val achievementsPoints: kotlin.Int,

    /* Banned. */
    @field:JsonProperty("banned")
    val banned: kotlin.Boolean,

    /* Account badges. */
    @field:JsonProperty("badges")
    val badges: kotlin.collections.List<kotlin.Any>? = null,

    /* Ban reason. */
    @field:JsonProperty("ban_reason")
    val banReason: kotlin.String? = null

)

