/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.AccountStatus

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param position Position in the leaderboard.
 * @param account Account name.
 * @param status Member status.
 * @param achievementsPoints Achievements points.
 * @param gold Gold in the account.
 */


data class AccountLeaderboardSchema (

    /* Position in the leaderboard. */
    @field:JsonProperty("position")
    val position: kotlin.Int,

    /* Account name. */
    @field:JsonProperty("account")
    val account: kotlin.String,

    /* Member status. */
    @field:JsonProperty("status")
    val status: AccountStatus,

    /* Achievements points. */
    @field:JsonProperty("achievements_points")
    val achievementsPoints: kotlin.Int,

    /* Gold in the account. */
    @field:JsonProperty("gold")
    val gold: kotlin.Int

)

