/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.AchievementRewardsSchema
import com.tellenn.artifacts.api.models.AchievementType
import com.tellenn.artifacts.api.models.Target

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Name of the achievement.
 * @param code Code of the achievement. 
 * @param description Description of the achievement.
 * @param points Points of the achievement. Used for the leaderboard.
 * @param type Type of achievement.
 * @param target 
 * @param total Total to do.
 * @param rewards Rewards.
 */


data class AchievementSchema (

    /* Name of the achievement. */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* Code of the achievement.  */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Description of the achievement. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* Points of the achievement. Used for the leaderboard. */
    @field:JsonProperty("points")
    val points: kotlin.Int,

    /* Type of achievement. */
    @field:JsonProperty("type")
    val type: AchievementType,

    @field:JsonProperty("target")
    val target: Target,

    /* Total to do. */
    @field:JsonProperty("total")
    val total: kotlin.Int,

    /* Rewards. */
    @field:JsonProperty("rewards")
    val rewards: AchievementRewardsSchema

)

