/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.MapSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Name of the event.
 * @param code Code of the event.
 * @param map Map of the event.
 * @param previousMap Previous map skin.
 * @param duration Duration in minutes.
 * @param expiration Expiration datetime.
 * @param createdAt Start datetime.
 */


data class ActiveEventSchema (

    /* Name of the event. */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* Code of the event. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Map of the event. */
    @field:JsonProperty("map")
    val map: MapSchema,

    /* Previous map skin. */
    @field:JsonProperty("previous_map")
    val previousMap: MapSchema,

    /* Duration in minutes. */
    @field:JsonProperty("duration")
    val duration: kotlin.Int,

    /* Expiration datetime. */
    @field:JsonProperty("expiration")
    val expiration: java.time.OffsetDateTime,

    /* Start datetime. */
    @field:JsonProperty("created_at")
    val createdAt: java.time.OffsetDateTime

)

