/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param username Your desired username.
 * @param password Your password.
 * @param email Your email.
 */


data class AddAccountSchema (

    /* Your desired username. */
    @field:JsonProperty("username")
    val username: kotlin.String,

    /* Your password. */
    @field:JsonProperty("password")
    val password: kotlin.String,

    /* Your email. */
    @field:JsonProperty("email")
    val email: kotlin.String

)

