/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param message Announcement text.
 * @param createdAt Datetime of the announcement.
 */


data class AnnouncementSchema (

    /* Announcement text. */
    @field:JsonProperty("message")
    val message: kotlin.String,

    /* Datetime of the announcement. */
    @field:JsonProperty("created_at")
    val createdAt: java.time.OffsetDateTime? = null

)

