/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.BadgeConditionSchema
import com.tellenn.artifacts.api.models.Season

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Code of the badge. This is the badge's unique identifier (ID).
 * @param description Description of the badge.
 * @param conditions Conditions to get the badge.
 * @param season 
 */


data class BadgeSchema (

    /* Code of the badge. This is the badge's unique identifier (ID). */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Description of the badge. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* Conditions to get the badge. */
    @field:JsonProperty("conditions")
    val conditions: kotlin.collections.List<BadgeConditionSchema>,

    @field:JsonProperty("season")
    val season: Season? = null

)

