/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.Quantity

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Code of the condition.
 * @param quantity 
 */


data class BadgeConditionSchema (

    /* Code of the condition. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    @field:JsonProperty("quantity")
    val quantity: Quantity

)

