/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CharacterSchema
import com.tellenn.artifacts.api.models.CooldownSchema
import com.tellenn.artifacts.api.models.SimpleItemSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cooldown Cooldown details.
 * @param items Items details.
 * @param bank Items in your banks.
 * @param character Player details.
 */


data class BankItemTransactionSchema (

    /* Cooldown details. */
    @field:JsonProperty("cooldown")
    val cooldown: CooldownSchema,

    /* Items details. */
    @field:JsonProperty("items")
    val items: kotlin.collections.List<SimpleItemSchema>,

    /* Items in your banks. */
    @field:JsonProperty("bank")
    val bank: kotlin.collections.List<SimpleItemSchema>,

    /* Player details. */
    @field:JsonProperty("character")
    val character: CharacterSchema

)

