/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param slots Maximum slots in your bank.
 * @param expansions Bank expansions.
 * @param nextExpansionCost Next expansion cost.
 * @param gold Quantity of gold in your bank.
 */


data class BankSchema (

    /* Maximum slots in your bank. */
    @field:JsonProperty("slots")
    val slots: kotlin.Int,

    /* Bank expansions. */
    @field:JsonProperty("expansions")
    val expansions: kotlin.Int,

    /* Next expansion cost. */
    @field:JsonProperty("next_expansion_cost")
    val nextExpansionCost: kotlin.Int,

    /* Quantity of gold in your bank. */
    @field:JsonProperty("gold")
    val gold: kotlin.Int

)

