/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param currentPassword Your password.
 * @param newPassword New password.
 */


data class ChangePassword (

    /* Your password. */
    @field:JsonProperty("current_password")
    val currentPassword: kotlin.String,

    /* New password. */
    @field:JsonProperty("new_password")
    val newPassword: kotlin.String

)

