/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CharacterSchema
import com.tellenn.artifacts.api.models.CooldownSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cooldown Cooldown details.
 * @param skin Craft details.
 * @param character Player details.
 */


data class ChangeSkinCharacterDataSchema (

    /* Cooldown details. */
    @field:JsonProperty("cooldown")
    val cooldown: CooldownSchema,

    /* Craft details. */
    @field:JsonProperty("skin")
    val skin: kotlin.String,

    /* Player details. */
    @field:JsonProperty("character")
    val character: CharacterSchema

)

