/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: men1,men2,men3,women1,women2,women3,corrupted1,zombie1
 */

enum class CharacterSkin(val value: kotlin.String) {

    @JsonProperty(value = "men1")
    men1("men1"),

    @JsonProperty(value = "men2")
    men2("men2"),

    @JsonProperty(value = "men3")
    men3("men3"),

    @JsonProperty(value = "women1")
    women1("women1"),

    @JsonProperty(value = "women2")
    women2("women2"),

    @JsonProperty(value = "women3")
    women3("women3"),

    @JsonProperty(value = "corrupted1")
    corrupted1("corrupted1"),

    @JsonProperty(value = "zombie1")
    zombie1("zombie1");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CharacterSkin) "$data" else null

        /**
         * Returns a valid [CharacterSkin] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CharacterSkin? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

