/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CharacterSchema
import com.tellenn.artifacts.api.models.CooldownSchema
import com.tellenn.artifacts.api.models.MapSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cooldown Cooldown details
 * @param destination Destination details.
 * @param character Character details.
 */


data class CharacterMovementDataSchema (

    /* Cooldown details */
    @field:JsonProperty("cooldown")
    val cooldown: CooldownSchema,

    /* Destination details. */
    @field:JsonProperty("destination")
    val destination: MapSchema,

    /* Character details. */
    @field:JsonProperty("character")
    val character: CharacterSchema

)

