/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.ConditionOperator

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Condition code.
 * @param `operator` Condition operator.
 * @param `value` Condition value.
 */


data class ConditionSchema (

    /* Condition code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Condition operator. */
    @field:JsonProperty("operator")
    val `operator`: ConditionOperator,

    /* Condition value. */
    @field:JsonProperty("value")
    val `value`: kotlin.Int

)

