/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.ActionType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param totalSeconds The total seconds of the cooldown.
 * @param remainingSeconds The remaining seconds of the cooldown.
 * @param startedAt The start of the cooldown.
 * @param expiration The expiration of the cooldown.
 * @param reason The reason of the cooldown.
 */


data class CooldownSchema (

    /* The total seconds of the cooldown. */
    @field:JsonProperty("total_seconds")
    val totalSeconds: kotlin.Int,

    /* The remaining seconds of the cooldown. */
    @field:JsonProperty("remaining_seconds")
    val remainingSeconds: kotlin.Int,

    /* The start of the cooldown. */
    @field:JsonProperty("started_at")
    val startedAt: java.time.OffsetDateTime,

    /* The expiration of the cooldown. */
    @field:JsonProperty("expiration")
    val expiration: java.time.OffsetDateTime,

    /* The reason of the cooldown. */
    @field:JsonProperty("reason")
    val reason: ActionType

)

