/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.ActiveEventSchema
import com.tellenn.artifacts.api.models.Page
import com.tellenn.artifacts.api.models.Pages
import com.tellenn.artifacts.api.models.Size
import com.tellenn.artifacts.api.models.Total

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `data` 
 * @param total 
 * @param page 
 * @param propertySize 
 * @param pages 
 */


data class DataPageActiveEventSchema (

    @field:JsonProperty("data")
    val `data`: kotlin.collections.List<ActiveEventSchema>,

    @field:JsonProperty("total")
    val total: Total,

    @field:JsonProperty("page")
    val page: Page,

    @field:JsonProperty("size")
    val propertySize: Size,

    @field:JsonProperty("pages")
    val pages: Pages? = null

)

