/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param x The x coordinate of the destination.
 * @param y The y coordinate of the destination.
 */


data class DestinationSchema (

    /* The x coordinate of the destination. */
    @field:JsonProperty("x")
    val x: kotlin.Int,

    /* The y coordinate of the destination. */
    @field:JsonProperty("y")
    val y: kotlin.Int

)

