/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code The code of the item.
 * @param quantity The quantity of the item.
 */


data class DropSchema (

    /* The code of the item. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* The quantity of the item. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int

)

