/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Item code.
 * @param rate Chance rate. (1/rate)
 * @param minQuantity Minimum quantity.
 * @param maxQuantity Maximum quantity.
 */


data class DropRateSchema (

    /* Item code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Chance rate. (1/rate) */
    @field:JsonProperty("rate")
    val rate: kotlin.Int,

    /* Minimum quantity. */
    @field:JsonProperty("min_quantity")
    val minQuantity: kotlin.Int,

    /* Maximum quantity. */
    @field:JsonProperty("max_quantity")
    val maxQuantity: kotlin.Int

)

