/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: stat,other,heal,buff,debuff,special,gathering,teleport,gold
 */

enum class EffectSubtype(val value: kotlin.String) {

    @JsonProperty(value = "stat")
    stat("stat"),

    @JsonProperty(value = "other")
    other("other"),

    @JsonProperty(value = "heal")
    heal("heal"),

    @JsonProperty(value = "buff")
    buff("buff"),

    @JsonProperty(value = "debuff")
    debuff("debuff"),

    @JsonProperty(value = "special")
    special("special"),

    @JsonProperty(value = "gathering")
    gathering("gathering"),

    @JsonProperty(value = "teleport")
    teleport("teleport"),

    @JsonProperty(value = "gold")
    gold("gold");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EffectSubtype) "$data" else null

        /**
         * Returns a valid [EffectSubtype] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EffectSubtype? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

