/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.EffectSubtype
import com.tellenn.artifacts.api.models.EffectType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Name of the effect.
 * @param code The code of the effect. This is the effect's unique identifier (ID).
 * @param description Description of the effect. This is a brief description of the effect.
 * @param type Type of the effect.
 * @param subtype Subtype of the effect.
 */


data class EffectSchema (

    /* Name of the effect. */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* The code of the effect. This is the effect's unique identifier (ID). */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Description of the effect. This is a brief description of the effect. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* Type of the effect. */
    @field:JsonProperty("type")
    val type: EffectType,

    /* Subtype of the effect. */
    @field:JsonProperty("subtype")
    val subtype: EffectSubtype

)

