/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CharacterSchema
import com.tellenn.artifacts.api.models.CooldownSchema
import com.tellenn.artifacts.api.models.ItemSchema
import com.tellenn.artifacts.api.models.ItemSlot

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cooldown Cooldown details.
 * @param slot Item slot.
 * @param item Item details.
 * @param character Player details.
 */


data class EquipRequestSchema (

    /* Cooldown details. */
    @field:JsonProperty("cooldown")
    val cooldown: CooldownSchema,

    /* Item slot. */
    @field:JsonProperty("slot")
    val slot: ItemSlot,

    /* Item details. */
    @field:JsonProperty("item")
    val item: ItemSchema,

    /* Player details. */
    @field:JsonProperty("character")
    val character: CharacterSchema

)

