/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param x Position X of the map.
 * @param y Position Y of the map.
 * @param skin Map skin of the map
 */


data class EventMapSchema (

    /* Position X of the map. */
    @field:JsonProperty("x")
    val x: kotlin.Int,

    /* Position Y of the map. */
    @field:JsonProperty("y")
    val y: kotlin.Int,

    /* Map skin of the map */
    @field:JsonProperty("skin")
    val skin: kotlin.String

)

