/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.EventContentSchema
import com.tellenn.artifacts.api.models.EventMapSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Name of the event.
 * @param code Code of the event.
 * @param content Content of the event.
 * @param maps Map list of the event.
 * @param duration Duration in minutes.
 * @param rate Rate spawn of the event. (1/rate every minute)
 */


data class EventSchema (

    /* Name of the event. */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* Code of the event. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Content of the event. */
    @field:JsonProperty("content")
    val content: EventContentSchema,

    /* Map list of the event. */
    @field:JsonProperty("maps")
    val maps: kotlin.collections.List<EventMapSchema>,

    /* Duration in minutes. */
    @field:JsonProperty("duration")
    val duration: kotlin.Int,

    /* Rate spawn of the event. (1/rate every minute) */
    @field:JsonProperty("rate")
    val rate: kotlin.Int

)

