/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.DropSchema
import com.tellenn.artifacts.api.models.FightResult

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param xp The amount of xp gained from the fight.
 * @param gold The amount of gold gained from the fight.
 * @param drops The items dropped from the fight.
 * @param turns Numbers of the turns of the combat.
 * @param logs The fight logs.
 * @param result The result of the fight.
 */


data class FightSchema (

    /* The amount of xp gained from the fight. */
    @field:JsonProperty("xp")
    val xp: kotlin.Int,

    /* The amount of gold gained from the fight. */
    @field:JsonProperty("gold")
    val gold: kotlin.Int,

    /* The items dropped from the fight. */
    @field:JsonProperty("drops")
    val drops: kotlin.collections.List<DropSchema>,

    /* Numbers of the turns of the combat. */
    @field:JsonProperty("turns")
    val turns: kotlin.Int,

    /* The fight logs. */
    @field:JsonProperty("logs")
    val logs: kotlin.collections.List<kotlin.String>,

    /* The result of the fight. */
    @field:JsonProperty("result")
    val result: FightResult

)

