/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id Order id.
 * @param quantity Item quantity.
 */


data class GEBuyOrderSchema (

    /* Order id. */
    @field:JsonProperty("id")
    val id: kotlin.String,

    /* Item quantity. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int

)

