/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id Order id.
 * @param seller Seller account name.
 * @param code Item code.
 * @param quantity Item quantity.
 * @param price Item price per unit.
 * @param createdAt Order created at.
 */


data class GEOrderSchema (

    /* Order id. */
    @field:JsonProperty("id")
    val id: kotlin.String,

    /* Seller account name. */
    @field:JsonProperty("seller")
    val seller: kotlin.String,

    /* Item code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Item quantity. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int,

    /* Item price per unit. */
    @field:JsonProperty("price")
    val price: kotlin.Int,

    /* Order created at. */
    @field:JsonProperty("created_at")
    val createdAt: java.time.OffsetDateTime

)

