/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param orderId Order id.
 * @param seller Seller account name.
 * @param buyer Buyer account name.
 * @param code Item code.
 * @param quantity Item quantity.
 * @param price Item price per unit.
 * @param soldAt Sale datetime.
 */


data class GeOrderHistorySchema (

    /* Order id. */
    @field:JsonProperty("order_id")
    val orderId: kotlin.String,

    /* Seller account name. */
    @field:JsonProperty("seller")
    val seller: kotlin.String,

    /* Buyer account name. */
    @field:JsonProperty("buyer")
    val buyer: kotlin.String,

    /* Item code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Item quantity. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int,

    /* Item price per unit. */
    @field:JsonProperty("price")
    val price: kotlin.Int,

    /* Sale datetime. */
    @field:JsonProperty("sold_at")
    val soldAt: java.time.OffsetDateTime

)

