/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id Order id.
 * @param createdAt Order created at.
 * @param code Item code.
 * @param quantity Item quantity.
 * @param price Item price per unit.
 * @param totalPrice Total price.
 * @param tax Listing tax (3%, minimum 1)
 */


data class GEOrderCreatedSchema (

    /* Order id. */
    @field:JsonProperty("id")
    val id: kotlin.String,

    /* Order created at. */
    @field:JsonProperty("created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Item code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Item quantity. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int,

    /* Item price per unit. */
    @field:JsonProperty("price")
    val price: kotlin.Int,

    /* Total price. */
    @field:JsonProperty("total_price")
    val totalPrice: kotlin.Int,

    /* Listing tax (3%, minimum 1) */
    @field:JsonProperty("tax")
    val tax: kotlin.Int

)

