/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param quantity Gold quantity.
 * @param character Character name. The name of the character who will receive the gold.
 */


data class GiveGoldSchema (

    /* Gold quantity. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int,

    /* Character name. The name of the character who will receive the gold. */
    @field:JsonProperty("character")
    val character: kotlin.String

)

