/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.SimpleItemSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param items List of items to give
 * @param character Character name. The name of the character who will receive the items.
 */


data class GiveItemsSchema (

    /* List of items to give */
    @field:JsonProperty("items")
    val items: kotlin.collections.List<SimpleItemSchema>,

    /* Character name. The name of the character who will receive the items. */
    @field:JsonProperty("character")
    val character: kotlin.String

)

