/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CharacterSchema
import com.tellenn.artifacts.api.models.CooldownSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cooldown Cooldown details.
 * @param quantity Quantity of gold given.
 * @param receiverCharacter Character details of the receiving character.
 * @param character Character details.
 */


data class GiveGoldDataSchema (

    /* Cooldown details. */
    @field:JsonProperty("cooldown")
    val cooldown: CooldownSchema,

    /* Quantity of gold given. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int,

    /* Character details of the receiving character. */
    @field:JsonProperty("receiver_character")
    val receiverCharacter: CharacterSchema,

    /* Character details. */
    @field:JsonProperty("character")
    val character: CharacterSchema

)

