/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CharacterSchema
import com.tellenn.artifacts.api.models.CooldownSchema
import com.tellenn.artifacts.api.models.SimpleItemSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cooldown Cooldown details.
 * @param items Items given.
 * @param receiverCharacter Character details of the receiving character.
 * @param character Character details of the sending character.
 */


data class GiveItemDataSchema (

    /* Cooldown details. */
    @field:JsonProperty("cooldown")
    val cooldown: CooldownSchema,

    /* Items given. */
    @field:JsonProperty("items")
    val items: kotlin.collections.List<SimpleItemSchema>,

    /* Character details of the receiving character. */
    @field:JsonProperty("receiver_character")
    val receiverCharacter: CharacterSchema,

    /* Character details of the sending character. */
    @field:JsonProperty("character")
    val character: CharacterSchema

)

