/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.ValidationError

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param detail 
 */


data class HTTPValidationError (

    @field:JsonProperty("detail")
    val detail: kotlin.collections.List<ValidationError>? = null

)

