/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param slot Inventory slot identifier.
 * @param code Item code.
 * @param quantity Quantity in the slot.
 */


data class InventorySlot (

    /* Inventory slot identifier. */
    @field:JsonProperty("slot")
    val slot: kotlin.Int,

    /* Item code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Quantity in the slot. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int

)

