/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CraftSchema
import com.tellenn.artifacts.api.models.CraftSkill

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Craft information. If applicable.
 *
 * @param skill Skill required to craft the item.
 * @param level The skill level required to craft the item.
 * @param items List of items required to craft the item.
 * @param quantity Quantity of items crafted.
 */


data class ItemSchemaCraft (

    /* Skill required to craft the item. */
    @field:JsonProperty("skill")
    val skill: CraftSkill? = null,

    /* The skill level required to craft the item. */
    @field:JsonProperty("level")
    val level: kotlin.Any? = null,

    /* List of items required to craft the item. */
    @field:JsonProperty("items")
    val items: kotlin.Any? = null,

    /* Quantity of items crafted. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Any? = null

)

