/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CooldownExpiration
import com.tellenn.artifacts.api.models.LogType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param character Character name.
 * @param account Account character.
 * @param type Type of action.
 * @param description Description of action.
 * @param content 
 * @param cooldown Cooldown in seconds.
 * @param cooldownExpiration 
 * @param createdAt Datetime of creation.
 */


data class LogSchema (

    /* Character name. */
    @field:JsonProperty("character")
    val character: kotlin.String,

    /* Account character. */
    @field:JsonProperty("account")
    val account: kotlin.String,

    /* Type of action. */
    @field:JsonProperty("type")
    val type: LogType,

    /* Description of action. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    @field:JsonProperty("content")
    val content: kotlin.Any?,

    /* Cooldown in seconds. */
    @field:JsonProperty("cooldown")
    val cooldown: kotlin.Int,

    @field:JsonProperty("cooldown_expiration")
    val cooldownExpiration: CooldownExpiration,

    /* Datetime of creation. */
    @field:JsonProperty("created_at")
    val createdAt: java.time.OffsetDateTime

)

