/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.MapContentType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param type Type of the content.
 * @param code Code of the content.
 */


data class MapContentSchema (

    /* Type of the content. */
    @field:JsonProperty("type")
    val type: MapContentType,

    /* Code of the content. */
    @field:JsonProperty("code")
    val code: kotlin.String

)

