/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.MapSchemaContent

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Name of the map.
 * @param skin Skin of the map.
 * @param x Position X of the map.
 * @param y Position Y of the map.
 * @param content 
 */


data class MapSchema (

    /* Name of the map. */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* Skin of the map. */
    @field:JsonProperty("skin")
    val skin: kotlin.String,

    /* Position X of the map. */
    @field:JsonProperty("x")
    val x: kotlin.Int,

    /* Position Y of the map. */
    @field:JsonProperty("y")
    val y: kotlin.Int,

    @field:JsonProperty("content")
    val content: MapSchemaContent

)

