/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CharacterSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param `data` List of your characters.
 */


data class MyCharactersListSchema (

    /* List of your characters. */
    @field:JsonProperty("data")
    val `data`: kotlin.collections.List<CharacterSchema>

)

