/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.BuyPrice
import com.tellenn.artifacts.api.models.SellPrice

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code The code of the NPC. This is the NPC's unique identifier (ID).
 * @param npc Code of the NPC that sells/buys the item.
 * @param currency Currency used to buy/sell the item. If it's not gold, it's the item code.
 * @param buyPrice 
 * @param sellPrice 
 */


data class NPCItem (

    /* The code of the NPC. This is the NPC's unique identifier (ID). */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Code of the NPC that sells/buys the item. */
    @field:JsonProperty("npc")
    val npc: kotlin.String,

    /* Currency used to buy/sell the item. If it's not gold, it's the item code. */
    @field:JsonProperty("currency")
    val currency: kotlin.String,

    @field:JsonProperty("buy_price")
    val buyPrice: BuyPrice,

    @field:JsonProperty("sell_price")
    val sellPrice: SellPrice

)

