/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Item code.
 * @param quantity Item quantity.
 * @param currency Currency used for the transaction.
 * @param price Item price.
 * @param totalPrice Total price of the transaction.
 */


data class NpcItemTransactionSchema (

    /* Item code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Item quantity. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int,

    /* Currency used for the transaction. */
    @field:JsonProperty("currency")
    val currency: kotlin.String,

    /* Item price. */
    @field:JsonProperty("price")
    val price: kotlin.Int,

    /* Total price of the transaction. */
    @field:JsonProperty("total_price")
    val totalPrice: kotlin.Int

)

