/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Item code.
 * @param quantity Item quantity.
 */


data class NpcMerchantBuySchema (

    /* Item code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Item quantity. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int

)

