/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.CharacterSchema
import com.tellenn.artifacts.api.models.CooldownSchema
import com.tellenn.artifacts.api.models.NpcItemTransactionSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param cooldown Cooldown details.
 * @param transaction Transaction details.
 * @param character Character details.
 */


data class NpcMerchantTransactionSchema (

    /* Cooldown details. */
    @field:JsonProperty("cooldown")
    val cooldown: CooldownSchema,

    /* Transaction details. */
    @field:JsonProperty("transaction")
    val transaction: NpcItemTransactionSchema,

    /* Character details. */
    @field:JsonProperty("character")
    val character: CharacterSchema

)

