/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.NPCType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name Name of the NPC.
 * @param code The code of the NPC. This is the NPC's unique identifier (ID).
 * @param description Description of the NPC.
 * @param type Type of the NPC.
 */


data class NPCSchema (

    /* Name of the NPC. */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* The code of the NPC. This is the NPC's unique identifier (ID). */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Description of the NPC. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* Type of the NPC. */
    @field:JsonProperty("type")
    val type: NPCType

)

