/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param token Password reset token.
 * @param newPassword Your new password.
 */


data class PasswordResetConfirmSchema (

    /* Password reset token. */
    @field:JsonProperty("token")
    val token: kotlin.String,

    /* Your new password. */
    @field:JsonProperty("new_password")
    val newPassword: kotlin.String

)

