/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param type Type of rate limit.
 * @param `value` Value of the rate limit.
 */


data class RateLimitSchema (

    /* Type of rate limit. */
    @field:JsonProperty("type")
    val type: kotlin.String,

    /* Value of the rate limit. */
    @field:JsonProperty("value")
    val `value`: kotlin.String

)

