/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.DropRateSchema
import com.tellenn.artifacts.api.models.GatheringSkill

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param name The name of the resource
 * @param code The code of the resource. This is the resource's unique identifier (ID).
 * @param skill The skill required to gather this resource.
 * @param level The skill level required to gather this resource.
 * @param drops The drops of this resource.
 */


data class ResourceSchema (

    /* The name of the resource */
    @field:JsonProperty("name")
    val name: kotlin.String,

    /* The code of the resource. This is the resource's unique identifier (ID). */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* The skill required to gather this resource. */
    @field:JsonProperty("skill")
    val skill: GatheringSkill,

    /* The skill level required to gather this resource. */
    @field:JsonProperty("level")
    val level: kotlin.Int,

    /* The drops of this resource. */
    @field:JsonProperty("drops")
    val drops: kotlin.collections.List<DropRateSchema>

)

