/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.SimpleItemSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param items Items rewards.
 * @param gold Gold rewards.
 */


data class RewardsSchema (

    /* Items rewards. */
    @field:JsonProperty("items")
    val items: kotlin.collections.List<SimpleItemSchema>,

    /* Gold rewards. */
    @field:JsonProperty("gold")
    val gold: kotlin.Int

)

