/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Skin code.
 * @param description Skin description.
 * @param requiredPoints Required achievement points to earn the skin.
 */


data class SeasonSkinSchema (

    /* Skin code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Skin description. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* Required achievement points to earn the skin. */
    @field:JsonProperty("required_points")
    val requiredPoints: kotlin.Int

)

