/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Badge code.
 * @param description Badge description.
 * @param requiredPoints Required achievement points to earn the badge.
 */


data class SeasonBadgeSchema (

    /* Badge code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Badge description. */
    @field:JsonProperty("description")
    val description: kotlin.String,

    /* Required achievement points to earn the badge. */
    @field:JsonProperty("required_points")
    val requiredPoints: kotlin.Int

)

