/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.SeasonBadgeSchema
import com.tellenn.artifacts.api.models.SeasonSkinSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param badges Season badges with required achievement points.
 * @param skins Season skins with required achievement points.
 * @param name Season name.
 * @param number Season number.
 * @param startDate Season start date.
 */


data class SeasonSchema (

    /* Season badges with required achievement points. */
    @field:JsonProperty("badges")
    val badges: kotlin.collections.List<SeasonBadgeSchema>,

    /* Season skins with required achievement points. */
    @field:JsonProperty("skins")
    val skins: kotlin.collections.List<SeasonSkinSchema>,

    /* Season name. */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Season number. */
    @field:JsonProperty("number")
    val number: kotlin.Int? = null,

    /* Season start date. */
    @field:JsonProperty("start_date")
    val startDate: java.time.OffsetDateTime? = null

)

