/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Effect code.
 * @param `value` Effect value.
 * @param description Description of the effect.
 */


data class SimpleEffectSchema (

    /* Effect code. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Effect value. */
    @field:JsonProperty("value")
    val `value`: kotlin.Int,

    /* Description of the effect. */
    @field:JsonProperty("description")
    val description: kotlin.String

)

