/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.DropSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param xp The amount of xp gained.
 * @param items Objects received.
 */


data class SkillInfoSchema (

    /* The amount of xp gained. */
    @field:JsonProperty("xp")
    val xp: kotlin.Int,

    /* Objects received. */
    @field:JsonProperty("items")
    val items: kotlin.collections.List<DropSchema>

)

