/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * Values: weaponcrafting,gearcrafting,jewelrycrafting,cooking,woodcutting,mining,alchemy,fishing
 */

enum class Skill(val value: kotlin.String) {

    @JsonProperty(value = "weaponcrafting")
    weaponcrafting("weaponcrafting"),

    @JsonProperty(value = "gearcrafting")
    gearcrafting("gearcrafting"),

    @JsonProperty(value = "jewelrycrafting")
    jewelrycrafting("jewelrycrafting"),

    @JsonProperty(value = "cooking")
    cooking("cooking"),

    @JsonProperty(value = "woodcutting")
    woodcutting("woodcutting"),

    @JsonProperty(value = "mining")
    mining("mining"),

    @JsonProperty(value = "alchemy")
    alchemy("alchemy"),

    @JsonProperty(value = "fishing")
    fishing("fishing");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Skill) "$data" else null

        /**
         * Returns a valid [Skill] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Skill? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

