/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.AnnouncementSchema
import com.tellenn.artifacts.api.models.RateLimitSchema
import com.tellenn.artifacts.api.models.SeasonSchema

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param version Game version.
 * @param serverTime Server time.
 * @param maxLevel Maximum level.
 * @param maxSkillLevel Maximum skill level.
 * @param charactersOnline Characters online.
 * @param announcements Server announcements.
 * @param rateLimits Rate limits.
 * @param season Current season details.
 */


data class StatusSchema (

    /* Game version. */
    @field:JsonProperty("version")
    val version: kotlin.String,

    /* Server time. */
    @field:JsonProperty("server_time")
    val serverTime: java.time.OffsetDateTime,

    /* Maximum level. */
    @field:JsonProperty("max_level")
    val maxLevel: kotlin.Int,

    /* Maximum skill level. */
    @field:JsonProperty("max_skill_level")
    val maxSkillLevel: kotlin.Int,

    /* Characters online. */
    @field:JsonProperty("characters_online")
    val charactersOnline: kotlin.Int,

    /* Server announcements. */
    @field:JsonProperty("announcements")
    val announcements: kotlin.collections.List<AnnouncementSchema>,

    /* Rate limits. */
    @field:JsonProperty("rate_limits")
    val rateLimits: kotlin.collections.List<RateLimitSchema>,

    /* Current season details. */
    @field:JsonProperty("season")
    val season: SeasonSchema? = null

)

