/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.RewardsSchema
import com.tellenn.artifacts.api.models.TaskType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Task objective.
 * @param type The type of task.
 * @param total The total required to complete the task.
 * @param rewards Rewards for completing the task.
 */


data class TaskSchema (

    /* Task objective. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* The type of task. */
    @field:JsonProperty("type")
    val type: TaskType,

    /* The total required to complete the task. */
    @field:JsonProperty("total")
    val total: kotlin.Int,

    /* Rewards for completing the task. */
    @field:JsonProperty("rewards")
    val rewards: RewardsSchema

)

