/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.RewardsSchema
import com.tellenn.artifacts.api.models.Skill1
import com.tellenn.artifacts.api.models.TaskType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param code Task objective.
 * @param level Task level.
 * @param type The type of task.
 * @param minQuantity Minimum amount of task.
 * @param maxQuantity Maximum amount of task.
 * @param skill 
 * @param rewards Rewards.
 */


data class TaskFullSchema (

    /* Task objective. */
    @field:JsonProperty("code")
    val code: kotlin.String,

    /* Task level. */
    @field:JsonProperty("level")
    val level: kotlin.Int,

    /* The type of task. */
    @field:JsonProperty("type")
    val type: TaskType,

    /* Minimum amount of task. */
    @field:JsonProperty("min_quantity")
    val minQuantity: kotlin.Int,

    /* Maximum amount of task. */
    @field:JsonProperty("max_quantity")
    val maxQuantity: kotlin.Int,

    @field:JsonProperty("skill")
    val skill: Skill1,

    /* Rewards. */
    @field:JsonProperty("rewards")
    val rewards: RewardsSchema

)

