/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.ItemSlot

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param slot Item slot.
 * @param quantity Item quantity. Applicable to utilities only.
 */


data class UnequipSchema (

    /* Item slot. */
    @field:JsonProperty("slot")
    val slot: ItemSlot,

    /* Item quantity. Applicable to utilities only. */
    @field:JsonProperty("quantity")
    val quantity: kotlin.Int? = 1

)

