/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.tellenn.artifacts.api.models

import com.tellenn.artifacts.api.models.ValidationErrorLocInner

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param loc 
 * @param msg 
 * @param type 
 */


data class ValidationError (

    @field:JsonProperty("loc")
    val loc: kotlin.collections.List<ValidationErrorLocInner>,

    @field:JsonProperty("msg")
    val msg: kotlin.String,

    @field:JsonProperty("type")
    val type: kotlin.String

)

